name: Main CI

on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: git clone
        uses: actions/checkout@v2   
 
   
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html
            git pull https://github.com/siliconii-hanjin/laravel.git 
